### Full-catchment configuration ###
train_cfg_file: ../trained_models/merit_conus_40yr/config.yaml
initial_state: zero  # zero: set initial states of the model to zero
verbose: 1  # 0: no output, 1: print output

# Simulation window
time_step: 1 day
start_time: 2000/01/01
end_time: 2005/12/31
