### Single-catchment configuration ###
catchment_id: 'cat-88306'
catchment_name: 'JRB-88306'

# Static catchment attributes
FW: 0.004622
HWSD_clay: 25.0
HWSD_sand: 33.0
T_clay: 20.0
uparea: 3.254
T_gravel: 10.0
meanelevation: 335.1
meanP: 991.3
HWSD_gravel: 15.0
seasonality_P: 0.1035
T_sand: 41.0
SoilGrids1km_silt: 38.06
permafrost: 0.0
snowfall_fraction: 0.1049
SoilGrids1km_sand: 38.65
Porosity: 0.01
T_silt: 39.0
glaciers: 0.0
HWSD_silt: 42.0
meanslope: 10.55
permeability: -15.05
seasonality_PET: 0.5703
ETPOT_Hargr: 1031.0
meanTa: 9.845
SoilGrids1km_clay: 23.31
snow_fraction: 0.02967
aridity: 1.041
NDVI: 0.594

config_model: dHBV_2_0/trained_models/merit_conus_40yr/config.yaml
stepwise: False  # True: stepwise inference, False: Single forward simulation on all data in one go
initial_state: zero  # zero: set initial states of the model to zero
dtype: float32
verbose: 1  # 0: no output, 1: print output

# Simulation window
time_step: 1 day
start_time: 2000/01/01
end_time: 2005/12/31
