name: bmi_dm
channels:
  - pytorch
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - bmipy
  - cpuonly
  - python=3.11
  - pytorch  # cpu only
  # - pytorch::pytorch-cuda=12.1
  # - pytorch::pytorch=2.5.1
  # - pytorch::pytorch-mutex=1.0
  # - pytorch::torchaudio=2.5.1
  # - pytorch::torchvision=0.20.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - pip=24.2
  - pandas
  - geopandas
  - matplotlib
  - pydantic
  - xarray
  - scipy
  - netcdf4
  - ipykernel
  - conda-forge::hydra-core
  - tqdm
  - conda-forge::polars
  - conda-forge::zarr
  - conda-forge::sympy=1.13.1
  - pytest
